import React from 'react';
import './mainContent.css';
import barbour from './barbour.png';
import suroq from './soroq.png';
import person from './human.png';
import effect from './mountain.png';
import not from './not.png';
import rect from './rect.png';
import any from './anything.png';
import circle from './circle.png';
import rectangle from './rectangle.png';
import flour from './flour.png';
import clinic from './clinic.png';
import river from './river.png';
import mm from './mm.png';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import next from './next.png'
import prev from './prev.png'
import mmand from './mmand.png'
import flower from './flower.png'
import plane from './plane.png'
import dots from './dots.png'
import kubik from './kubik.png'
import  travel from './travel.png'
import lock from './lock.png'

const MainContent = () => {
    return (
        <div className='container'>
            <div className='section-1 mt-5 container '>
                <h5 className='text-center for-w'>Trusted by world-class brands.</h5>
                <img src={barbour} className='barbour' alt='Barbour' />
                <h5 className='bor mx-auto mt-5 for-w'>  <span className='pad'>Meet our customers ></span></h5>
            </div>

            <div className='section-2 container'>
                <div className='left-content'>
                    <h2 className='fw-bold'>Grow 2.5x faster than <br /> your competitors.</h2>
                    <div className='d-flex mt-5'>
                        <button className="navbar-button">Book a demo</button>
                        <h4 className='link mt-2'>Meet our customers ></h4>
                    </div>
                    <p className='pwc-note mt-5'>*PwC audited methodology.</p>
                    <a href='#' className='report-link'>Read the report</a>
                </div>
                <div className='right-content'>
                    <div className='stats'>
                        <div className='stat-item'>
                            <h3>140%</h3>
                            <p>Qubit's top customers annual growth rate.</p>
                        </div>
                        <div className='stat-item'>
                            <h3>$20bn</h3>
                            <p>Online sales generated by our customers in 2020.</p>
                        </div>
                        <div className='stat-item'>
                            <h3>364</h3>
                            <p>Ecommerce stores are growing faster with Qubit.</p>
                        </div>
                        <div className='stat-item'>
                            <h3>9.5m</h3>
                            <p>Personalized experiences delivered every hour.</p>
                        </div>
                        <div className='stat-item'>
                            <h3>4.4m</h3>
                            <p>Shoppers influenced by Qubit every day.</p>
                        </div>
                        <div className='stat-item'>
                            <h3>$1.6bn</h3>
                            <p>Incremental revenue generated by our customers in 2020.*</p>
                        </div>
                    </div>
                </div>
            </div>

            <div className='section-3 container'>
                <h2 className='text-center'>Qubit CommerceAI.</h2>
                <p className='text-center'>The new way to drive growth.</p>
                <div className='features'>
                    <div className='feature-item'>
                        <img src={suroq} alt='More insight' className='mt-3' />
                        <h3>More insight</h3>
                        <p>Learn which products drive performance and which don't, through automated insights you can action.</p>
                    </div>
                    <div className='feature-item'>
                        <img src={person} alt='More personal' />
                        <h3>More personal</h3>
                        <p>Qubit CommerceAI generates a model per shopper to make every customer interaction more relevant.</p>
                    </div>
                    <div className='feature-item'>
                        <img src={effect} alt='More effective' />
                        <h3>More effective</h3>
                        <p>Qubit fuses data, intent, and design tools to enable your team to create more effective customer experiences.</p>
                    </div>
                </div>
            </div>

            <div className='section-4 container text-center  for-w'>
                <h1 className='for-w pt-5'>All the power. Easy to use.</h1>
                <p className='mt-4'>By collaborating with real ecommerce teams we've built the next-gen personalization tool. No code. No clunkiness.</p>
                <img src={not} alt="" className='not' />
                <div className='buttons'>
                    <button className="navbar-button mx-auto">Book a demo</button>
                    <button className="button2  ml-5">Book a demo</button>

                </div>
            </div>

            <div className='section-5 container'>
                <h2 className='text-center '>What you can do with Qubit.</h2>
                <div className='features-2 mt-4'>
                    <div className='feature-item-2'>
                        <img src={rect} alt='Product recommendations' />
                        <h3>1:1 Product recommendations</h3>
                        <p>Use deep learning recommendations to engage customers in seconds.</p>
                    </div>
                    <div className='feature-item-2'>
                        <img src={rectangle} alt='Product badging' />
                        <h3>1:1 Product badging</h3>
                        <p>Guide discovery with personalized product badging. Push sales with social proofing.</p>
                    </div>
                    <div className='feature-item-2'>
                        <img src={circle} alt='Personalized content' />
                        <h3>Personalized content</h3>
                        <p>Your customers are unique. Present them with content that shows you know them.</p>
                    </div>
                    <div className='feature-item-2'>
                        <img src={suroq} alt='Product insights' />
                        <h3>Product insights</h3>
                        <p>A platform packed with insights helping you discover the hard-hitting things you can do next.</p>
                    </div>
                    <div className='feature-item-2'>
                        <img src={any} alt='CommerceAI' />
                        <h3>CommerceAI</h3>
                        <p>Your customer's behavioral data is telling you a story. Use predictive and affinity-based algorithms to serve them better.</p>
                    </div>
                    <div className='feature-item-2'>
                        <img src={flour} alt='Platform integrations' />
                        <h3>Platform integrations</h3>
                        <p>Connect Qubit to any tool via API. Import data or trigger an experience on any platform.</p>
                    </div>
                </div>
            </div>

            <div className='section-6 container'>
                <h1 className='text-center for-w'>Trusted by leading brands.</h1>

                <div id="carouselExampleInterval" className="carousel slide mt-5" data-bs-ride="carousel">
                    <div className="carousel-inner">

                        {/* SLIDE 1 */}
                        <div className="carousel-item active" data-bs-interval="3000">
                            <div className="d-flex justify-content-between">

                                <div className='card'>
                                    <img src={clinic} alt='Clinique' />
                                    <h3 className='for-w'>CLINIQUE</h3>
                                    <p>Clinique builds <br /> relationships with <br /> millions of customers <br /> each year.</p>
                                </div>

                                <div className='card'>
                                    <img src={river} alt='River Island' />
                                    <h3>RIVER ISLAND</h3>
                                    <p>River Island <br /> transforms the <br /> customer experience <br /> with personalization.</p>
                                </div>

                                <div className='card mandm-card'>
                                    <img src={mm} alt='MandM Direct' />
                                    <img className='mmand' src={mmand} alt="M and M" />
                                    <p>MandM Direct drives <br /> increase in revenue with <br /> deep learning recs.</p>
                                </div>

                            </div>
                        </div>

                        {/* SLIDE 2 */}
                        <div className="carousel-item" data-bs-interval="3000">
                            <div className="d-flex justify-content-between">

                                <div className='card mandm-card'>
                                    <img src={mm} alt='MandM Direct' />
                                    <img className='mmand' src={mmand} alt="M and M" />
                                    <p>MandM Direct drives <br /> increase in revenue with <br /> deep learning recs.</p>
                                </div>

                                <div className='card'>
                                    <img src={clinic} alt='Clinique' />
                                    <h3 className='for-w '>CLINIQUE</h3>
                                    <p>Clinique builds <br /> relationships with <br /> millions of customers <br /> each year.</p>
                                </div>

                                <div className='card'>
                                    <img src={river} alt='River Island' />
                                    <h3>RIVER ISLAND</h3>
                                    <p>River Island <br /> transforms the <br /> customer experience <br /> with personalization.</p>
                                </div>

                            </div>
                        </div>
                    </div>

                    {/* Controls */}
                    <button className="carousel-control-prev control-btn" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
                        <img src={prev} alt="Previous" />
                        <span className="visually-hidden">Previous</span>
                    </button>

                    <button className="carousel-control-next control-btn" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
                        <img src={next} alt="Next" />
                        <span className="visually-hidden">Next</span>
                    </button>
                </div>
            </div>




            <div className="section-7 container">
                <h1 className="text-center for-w">We specialize in your industry.</h1>
                <p className="text-center">Learn how we are delivering personalization at scale across sectors.</p>
                <div className="card-container mt-5">
                    <div className="card-specialized ">
                        <div className='d-flex'>
                        <img src={flower} alt="Beauty and cosmetics" className="card-icon" />
                        <h3 className="card-title">Beauty and cosmetics</h3>
                        </div>
                        <p className="card-description">
                            Discover relevant products. Push samples. Upsell and <br/> replenish.
                        </p>
                        <p className="card-link">
                            Explore our solutions for beauty and cosmetics.
                        </p>
                    </div>
                    <div className="card-specialized ">
                        <div className='d-flex'>
                            <img src={dots} alt="Beauty and cosmetics" className="card-icon mt-1" />
                            <h3 className="card-title">Fashion</h3>
                        </div>
                        <p className="card-description">
                            Supercharge merchandising. Reach your best  <br/> customers.
                        </p>
                        <p className="card-link">
                            Explore our solutions for fashion.
                        </p>
                    </div>
                    <div className="card-specialized ">
                        <div className='d-flex'>
                            <img src={lock} alt="Beauty and cosmetics" className="card-icon" />
                            <h3 className="card-title">Luxury</h3>
                        </div>
                        <p className="card-description mt-1">
                            Drive brand experience online. Look after your VIPs.
                        </p>
                        <p className="card-link mt-5">
                            Explore our solutions for luxury.
                        </p>
                    </div>
                    <div className="card-specialized ">
                        <div className='d-flex'>
                            <img src={plane} alt="Beauty and cosmetics" className="card-icon mt-1" />
                            <h3 className="card-title">Airlines</h3>
                        </div>
                        <p className="card-description">
                            Increase loyalty. Boost ancillary sales. Capture every <br/> opportunity.
                        </p>
                        <p className="card-link">
                            Explore our solutions for airlines.
                        </p>
                    </div>
                    <div className="card-specialized ">
                        <div className='d-flex'>
                            <img src={travel} alt="Beauty and cosmetics" className="card-icon" />
                            <h3 className="card-title">Travel & Tourism</h3>
                        </div>
                        <p className="card-description mt-3">
                            Be persuasive. Inspire travellers. Drive revenue.
                        </p>
                        <p className="card-link mt-4">
                            Explore our solutions for travel and tourism.
                        </p>
                    </div>
                    <div className="card-specialized ">
                        <div className='d-flex'>
                            <img src={kubik} alt="Beauty and cosmetics" className="card-icon" />
                            <h3 className="card-title">Online betting</h3>
                        </div>
                        <p className="card-description">
                            Bring events to life. Personalize in real time. Be <br/> responsible.
                        </p>
                        <p className="card-link">
                            Explore our solutions for online betting.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default MainContent;
